### ISSUE TITLE
Please add Cargo.lock into your .gitignore

### ISSUE THREAD

**Issue by BooterT** [thunderstorm010/topside#1]
Hey Mr. Rust Master,
Your Cargo.lock file is just a bullshit including your Cargo's shit information. I don't have to see your Cargo's garbage. Also I don't want to waste my bandwidth while cloning the project because of a garbage file.
Please add Cargo.lock in .gitignore,
With my best wishes and love <3
rehtoM ruoY kcuF
Berat Gökgöz

**Comment by thunderstorm010** [comment]
Definitely you haven't read [this](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries)
