### ISSUE TITLE
ros package missing

### ISSUE THREAD

**Issue by BooterT** [thunderstorm010/topside#2]
The subdirectory ros points to nowhere. It isn't clickable and looks like an empty folder when cloned.
Please fill in the blanks sir.
.rehtom ruoy kcuf lliw I
Yours sincerely...

**Comment by thunderstorm010** [comment]
Fixed at https://github.com/thunderstorm010/topside/commit/a864f6e8ccc2ad4e34b0835df19e18663c612761
